version: "3.8"

services:
  tomcat:
    image: bitnami/tomcat:9.0
    ports:
      - "8080:8080"
    volumes:
      - ./tomcat-users.xml:/opt/bitnami/tomcat/conf/tomcat-users.xml
    environment:
      - TOMCAT_ALLOW_REMOTE_MANAGEMENT=1