version: "3.8"

services:
  tomcat:
    image: bitnami/tomcat:latest
    ports:
      - "8080:8080"
    environment:
      - TOMCAT_ALLOW_REMOTE_MANAGEMENT=1
      - TOMCAT_USERNAME=manager
      - TOMCAT_PASSWORD=manager